spring:
  datasource:
    url: jdbc:mysql://85.215.45.13/qrush_db?sslmode=require&useSSL=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: qrush_user
    password: Wsd12Maukha2502#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
