spring:
  datasource:
    url: jdbc:mysql://qrush.mysql.database.azure.com/qrush?sslmode=require&useSSL=true&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: mintchev
    password: Dynamo1953
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
