name: Sync with GitLab

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push to GitLab
        run: |
          git remote add https://gitlab.com/qrush-dating/qrush-server.git
          git pull gitlab main  
          git push origin main
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
